# fly.toml app configuration file generated for the13thgeek-nodejs on 2024-11-29T19:41:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'the13thgeek-nodejs'
primary_region = 'yyz'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
